baseURL = "https://ciiiii.github.io/blog/"
languageCode = "zh-cn"
title = "ciii's blog"
theme = "base16"
isCJKLanguage = true
[permalinks]
  post = "/:year/:month/:title/"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
