baseURL = "https://ciii.tech"
languageCode = "zh-cn"
title = "ciii's blog"
theme = "base16"
hasCJKLanguage = true
pygmentsuseclasses = true
[permalinks]
  post = "/:year/:month/:title/"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[params]
  author = "ciii" 

  [params.valine]
    enable = true
    appId = ""
    appKey = ""
    notify = true
    verify = false
    avatar = 'retro'
    placeholder = '✒️说点什么吧，该评论支持Markdown语法'
    visitor = true
