baseURL = "https://ciii.tech"
languageCode = "zh-cn"
title = "ciii's blog"
theme = "base16"
hasCJKLanguage = true
[permalinks]
  post = "/:year/:month/:title/"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
