name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.0
        with:
          hugo-version: "0.59.1"

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_PUSH }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
