name: github pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.0
        with:
          hugo-version: "0.59.1"

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_PUSH }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public

      - name: Purge CDN Cache
        uses: 3stacks/cloudflare-purge-cache-action@1.0.1
        with:
          authToken: ${{ secrets.CLOUDFLARE_AUTH_TOKEN }}
          siteName: ciii.tech
          authEmail: allen.ccccnm@gmail.com
          fileList: '["https://ciii.tech/index.html"]'
